package lt.bit.products.ui.service.error;

public enum ErrorCode {
    VALUE_TOO_SHORT, EMPTY_VALUE, NEGATIVE_NUMBER, VALUE_TOO_LONG, PRODUCT_NOT_FOUND, VALUE_CONTAINS_DIGITS, FILE_TOO_LARGE, INVALID_FILE_TYPE
}